language: generic

sudo: required

services:

  - docker



before_install:

  - docker build -t mshukla/docker -f Dockerfile.dev .



script:

  - docker run -e CI=true mshukla/docker npm run test



deploy:

  provider: elasticbeanstalk

  region: "ap-south-1"

  app: "docker-react"

  env: "Dockerreact-env"

  bucket_name: "elasticbeanstalk-ap-south-1-051170420061"

  bucket_path: "docker-react"

  on:

    branch: master

  access_key_id: $AWS_ACCESS_KEY

  secret_access_key: "$AWS_SECRET_KEY"